version: '3.2'

services:
  db:
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
    ports: 
      - 5432:5432
  adminer: 
    image: adminer
    restart: always
    ports: 
      - 8123:8080